package AutoTest.Regex;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.junit.Test;

public class VarReplaceExp {
	  private final String regex="[\\s]*\\$[\\s]*\\{[\\s]*[_,a-z,A-Z,0-9]+[\\s]*\\}[\\s]*";
	  
	  private Pattern pattern=Pattern.compile(regex);
	  
	    /**
	     * 判断是否存在变量替换表达式
	     * @param regex
	     * @return
	     */
	    public boolean is_VarReplace_Exp(String var) {
	    	return pattern.matcher(var).find();
	    }
	    
	    /**
	     * 变量替换
	     */
	    public String return_Result(String regex,Map<String,String> currentline){
	    	return currentline.containsKey(RegexParser(regex))==true?currentline.get(RegexParser(regex)):"";
	    }
	    
	    /**
	     * 表达式解析
	     * @return
	     */
	    private String RegexParser(String regex){
	    	return regex.replaceAll(" ", "").substring(2, regex.replaceAll(" ", "").length()-1).trim();
	    }
	    
	    
	    /**
	     * 查询文本中的替换表达式
	     * @param content
	     * @return
	     */
	    public List<String> FindContentRegex(String content){
	    	Matcher m=pattern.matcher(content);
	    	Set<String> regexs=new HashSet<String>();
	    	while(m.find()) {
	    	  regexs.add(m.group());
	    	}
	    	List<String> l=new LinkedList<String>();
	    	Iterator<String> i=regexs.iterator();
	    	while(i.hasNext()){
	    		l.add(i.next());
	    	}
	    	return l;
	    }


	    @Test
	    public void testr() {
	    	System.out.println(is_VarReplace_Exp("{\r\n" + 
	    			"	\"success\": true,\r\n" + 
	    			"	\"statusCode\": \"find template success\",\r\n" + 
	    			"	\"message\": \"查找模版成功\",\r\n" + 
	    			"	\"resultParameters\": {},\r\n" + 
	    			"	\"templateDto\": {\r\n" + 
	    			"		\"parameters\": {},\r\n" + 
	    			"		\"currentPage\": null,\r\n" + 
	    			"		\"pageSize\": null,\r\n" + 
	    			"		\"userToken\": ${xyzz},\r\n" + 
	    			"		\"id\": \"jinxTemplate\",\r\n" + 
	    			"		\"name\": \"jinx的模板\",\r\n" + 
	    			"		\"createTime\": null,\r\n" + 
	    			"		\"lastUpdateTime\": null,\r\n" + 
	    			"		\"cacheStatus\": 0,\r\n" + 
	    			"		\"version\": \"v2\",\r\n" + 
	    			"		\"templateAlias\": null\r\n" + 
	    			"	},\r\n" + 
	    			"	\"hrForm\": null,\r\n" + 
	    			"	\"hrRelation\": {\r\n" + 
	    			"		\"relationCode\": \"jinxTemplate\",\r\n" + 
	    			"		\"relationName\": null,\r\n" + 
	    			"		\"relationJson\": null,\r\n" + 
	    			"		\"filePath\": \"M00/00/2D/rBCeNl6f6hWAdoRMAAAEUByHacc271.dat\",\r\n" + 
	    			"		\"flag\": 0\r\n" + 
	    			"	},\r\n" + 
	    			"	\"dataSetList\": [\r\n" + 
	    			"		{\r\n" + 
	    			"			\"dataSetCode\": \"jinxid1\",\r\n" + 
	    			"			\"dataSetName\": \"query_all\",\r\n" + 
	    			"			\"dataSetJson\": null,\r\n" + 
	    			"			\"filePath\": \"M00/00/2D/rBCeKl6f5-KAeNtFAAABo-WIZlE992.dat\"\r\n" + 
	    			"		}\r\n" + 
	    			"	],\r\n" + 
	    			"	\"templateList\": null,\r\n" + 
	    			"	\"recordsCount\": 0,\r\n" + 
	    			"	\"templateData\": \"UEsDBBQABgAIAAAAIQBBN4LPbgEAAAQFAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsVMluwjAQvVfqP0S+Vomhh6qqCBy6HFsk6AeYeJJYJLblGSj8fSdmUVWxCMElUWzPWybzPBit2iZZQkDjbC76WU8kYAunja1y8T39SJ9FgqSsVo2zkIs1oBgN7+8G07UHTLjaYi5qIv8iJRY1tAoz58HyTulCq4g/QyW9KuaqAvnY6z3JwlkCSyl1GGI4eINSLRpK3le8vFEyM1Ykr5tzHVUulPeNKRSxULm0+h9J6srSFKBdsWgZOkMfQGmsAahtMh8MM4YJELExFPIgZ4AGLyPdusq4MgrD2nh8YOtHGLqd4662dV/8O4LRkIxVoE/Vsne5auSPC/OZc/PsNMilrYktylpl7E73Cf54GGV89W8spPMXgc/oIJ4xkPF5vYQIc4YQad0A3rrtEfQcc60C6Anx9FY3F/AX+5QOjtQ4OI+c2gCXd2EXka469QwEgQzsQ3Jo2PaMHPmr2w7dnaJBH+CW8Q4b/gIAAP//AwBQSwMEFAAGAAgAAAAhALVVMCP0AAAATAIAAAsACAJfcmVscy8ucmVscyCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACskk1PwzAMhu9I/IfI99XdkBBCS3dBSLshVH6ASdwPtY2jJBvdvyccEFQagwNHf71+/Mrb3TyN6sgh9uI0rIsSFDsjtnethpf6cXUHKiZylkZxrOHEEXbV9dX2mUdKeSh2vY8qq7iooUvJ3yNG0/FEsRDPLlcaCROlHIYWPZmBWsZNWd5i+K4B1UJT7a2GsLc3oOqTz5t/15am6Q0/iDlM7NKZFchzYmfZrnzIbCH1+RpVU2g5abBinnI6InlfZGzA80SbvxP9fC1OnMhSIjQS+DLPR8cloPV/WrQ08cudecQ3CcOryPDJgosfqN4BAAD//wMAUEsDBBQABgAIAAAAIQCBPpSX8wAAALoCAAAaAAgBeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHMgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsUk1LxDAQvQv+hzB3m3YVEdl0LyLsVesPCMm0KdsmITN+9N8bKrpdWNZLLwNvhnnvzcd29zUO4gMT9cErqIoSBHoTbO87BW/N880DCGLtrR6CRwUTEuzq66vtCw6acxO5PpLILJ4UOOb4KCUZh6OmIkT0udKGNGrOMHUyanPQHcpNWd7LtOSA+oRT7K2CtLe3IJopZuX/uUPb9gafgnkf0fMZCUk8DXkA0ejUISv4wUX2CPK8/GZNec5rwaP6DOUcq0seqjU9fIZ0IIfIRx9/KZJz5aKZu1Xv4XRC+8opv9vyLMv072bkycfV3wAAAP//AwBQSwMEFAAGAAgAAAAhAOzE+h3hAQAAiAMAAA8AAAB4bC93b3JrYm9vay54bWysk02P2jAQhu+V+h8s34OTELKACKtSqIpUVauW7p6NMyEW/ohsZwFV/e+dJEq71V720JPtGfuZ9/XYq/urVuQZnJfWFDSZxJSAEbaU5lTQH4dP0ZwSH7gpubIGCnoDT+/X79+tLtadj9aeCQKML2gdQrNkzIsaNPcT24DBTGWd5gGX7sR844CXvgYIWrE0jnOmuTR0ICzdWxi2qqSArRWtBhMGiAPFA8r3tWz8SNPiLTjN3bltImF1g4ijVDLceiglWiz3J2MdPyq0fU1mIxmnr9BaCme9rcIEUWwQ+cpvErMkGSyvV5VU8DhcO+FN85XrroqiRHEfdqUMUBY0x6W9wD8B1zabVirMJlmWxpSt/7TiwRHEBnAPTj5zccMtlJRQ8VaFA7ZlLIjxPIuTpDvbtfBRwsX/xXRLcn2SprSXguKDuL2YX/rwkyxDXdA0TXPMD7HPIE91QHaaZ7MOzV6w+65jjX4kpnf7vXsJqLCP7TtDlLilxInbl704Nh4TXAl01w39xjxdJNOuBlzDFx/6kbROFvRnksUf7uJFFsW76SzK5os0mmfTNPqYbdPd7G633W1mv/5vL/FFLMfv0KmsuQsHx8UZP9E3qDbcY28HQ6gXL2ZUzcZT698AAAD//wMAUEsDBBQABgAIAAAAIQBFS7YC4AAAADABAAAUAAAAeGwvc2hhcmVkU3RyaW5ncy54bWycjzFKRDEURXvBPYTXO/kzhYgkmWJAmM5CFxD+fzM/8PMS894XZwuCWGlvobgAwcbtjM4yjOCAteXlcg/nmvlNHNQ1Fg6JLEwnDSikNnWB1hYuL86OTkCxeOr8kAgtbJBh7g4PDLOouiW20IvkU6257TF6nqSMVJtVKtFLjWWtORf0HfeIEgc9a5pjHX0gUG0aSSzMQI0UrkZc7LMzHJwRt3t72d49fN4+755ejRZncl89JLTnRa0SybKr1qBkk6scpUWi3zOgndE/jL+cr4/H7f37/zi6PnbfAAAA//8DAFBLAwQUAAYACAAAACEAO20yS8EAAABCAQAAIwAAAHhsL3dvcmtzaGVldHMvX3JlbHMvc2hlZXQxLnhtbC5yZWxzhI/BisIwFEX3A/5DeHuT1oUMQ1M3IrhV5wNi+toG25eQ9xT9e7McZcDl5XDP5Tab+zypG2YOkSzUugKF5GMXaLDwe9otv0GxOOrcFAktPJBh0y6+mgNOTkqJx5BYFQuxhVEk/RjDfsTZsY4JqZA+5tlJiXkwyfmLG9Csqmpt8l8HtC9Ote8s5H1Xgzo9Uln+7I59Hzxuo7/OSPLPhEk5kGA+okg5yEXt8oBiQet39p5rfQ4Epm3My/P2CQAA//8DAFBLAwQUAAYACAAAACEAy6omh6QGAACTGgAAEwAAAHhsL3RoZW1lL3RoZW1lMS54bWzsWVuLGzcUfi/0Pwzz7vg248sSb7DHdtJmNwlZJyWPsi17lNWMzEjejQmBkDyVQqGQlrwUSl/6UEoDDTS0D/0v3ZKQpj+iR5qxR1rL2STdlLRkd1lmNJ+OPp1z9Ol29tytiDoHOOGExS23fKbkOjgesTGJpy332qBfaLgOFygeI8pi3HIXmLvntj/84CzaEiGOsAP1Y76FWm4oxGyrWOQjKEb8DJvhGL5NWBIhAa/JtDhO0CHYjWixUirVihEisevEKAKzlycTMsLOH09+ff7tw9/vfgZ/7vayjR6FhmLBZcGIJnuyBWxUVNjxflki+IIHNHEOEG250NyYHQ7wLeE6FHEBH1puSf24xe2zRbSVVaJiQ12tXl/9ZPWyCuP9imozmQ5XjXqe79XaK/sKQMU6rlfv1Xq1lT0FQKMR9DTlotv0O81O18+wGih9tNju1rvVsoHX7FfXOLd9+WvgFSi1763h+/0AvGjgFSjF+xaf1CuBZ+AVKMXX1vD1Urvr1Q28AoWUxPtr6JJfqwbL3q4gE0YvWOFN3+vXK5nxHAXZsMou2cSExWJTrkXoJkv6AJBAigSJHbGY4QkaQTIHiJJhQpwdMg0h8WYoZhyKS5VSv1SF//LXU0/KI2gLI6225AVM+FqR5OPwUUJmouV+DFZdDfL0yZOje4+P7v18dP/+0b0fs7aVKaPeBRRP9Xovvvvir6/vOn/+9M2LB1+mTR/Hcx3/7IdPn/3y28vMQ49zVzz96tGzx4+ePvz8+fcPLNbbCRrq8AGJMHcu4UPnKouggxb+eJi8Xo1BiIhRA4Vg22K6J0IDeGmBqA3XwaYLryegMjbg+flNg+temMwFsbR8MYwM4C5jtMMSqwMuyrY0Dw/m8dTeeDLXcVcROrC1HaDYCHBvPgN5JTaTQYgNmlcoigWa4hgLR35j+xhbeneDEMOvu2SUMM4mwrlBnA4iVpcMyNBIpLzSBRJBXBY2ghBqwze7150Oo7Zed/GBiYRhgaiF/ABTw43n0VygyGZygCKqO3wHidBGcm+RjHRcjwuI9BRT5vTGmHNbncsJ9FcL+kVQGHvYd+kiMpGJIPs2mzuIMR3ZZftBiKKZlTOJQx37Ed+HFEXOFSZs8F1mjhD5DnFA8cZwXyfYCPfJQnANxFWnlCeI/DJPLLE8j5k5Hhd0grBSGdB+Q9IjEp+o78eU3f93lN2u0aeg6XbD/0TN2wmxjqkLxzR8E+4/qNxdNI+vYBgs6zPXe+F+L9zu/164N43l05frXKFBvPO1ulq5RxsX7hNC6Z5YULzD1dqdw7w07kOh2lSoneVqIzcL4THbJhi4aYJUHSdh4hMiwr0QzWCBX1bb0CnPTE+5M2Mc1v2qWO2L8THbavcwj3bZON2vlstyb5qKB0ciLy/5q3LYa4gUXavne7CVebWrnaq98pKArPs6JLTGTBJVC4n6shCi8DISqmenwqJpYdGQ5pehWkZx5QqgtooKLJwcWG61XN9LzwFgS4UoHss4pUcCy+jK4JxqpDc5k+oZAKuIZQbkkW5Krhu7J3uXptorRNogoaWbSUJLwxCNcZad+sHJaca6mYfUoCddsRwNOY16423EWorIMW2gsa4UNHYOW26t6sMR2QjNWu4E9v3wGM0gd7hc8CI6hTO0kUjSAf8myjJLuOgiHqYOV6KTqkFEBE4cSqKWK7u/ygYaKw1R3MoVEIR3llwTZOVdIwdBN4OMJxM8EnrYtRLp6fQVFD7VCutXVf3NwbImm0O498LxoTOk8+QqghTz62XpwDHhcPxTTr05JnCeuRKyPP+OTUyZ7OoHiiqH0nJEZyHKZhRdzFO4EtEVHfW28oH2lvUZHLruwuFUTrD/eNY9eaqWntNEM58zDVWRs6ZdTN/eJK+xyidRg1Uq3WrbwHOtay61DhLVOkucMOu+woSgUcsbM6hJxusyLDU7KzWpneKCQPNEbYPfVnOE1RNvOvNDveNZKyeI5bpSJb66/9DvJtjwJohHF06B51RwFUq4eUgQLPrSc+RUNmCI3BLZGhGenHlCWu7tkt/2goofFEoNv1fwql6p0PDb1ULb96vlnl8udTuVOzCxiDAq++ndSx8Oougiu4FR5Wu3MNHyrO3MiEVFpm5Zioq4uoUpV2y3MAN5v+I6BETndq3Sb1abnVqhWW33C1630yg0g1qn0K0F9W6/G/iNZv+O6xwosNeuBl6t1yjUykFQ8GolSb/RLNS9SqXt1duNnte+ky1joOepfGS+APcqXtt/AwAA//8DAFBLAwQUAAYACAAAACEA2BDcIhcDAAAGCAAADQAAAHhsL3N0eWxlcy54bWysVc1u00AQviPxDqu9u/5JHJLIdtU0tVQJJKQWievGXier7o+13hQHxI0LT8KJe8WFp0HlMZj1T2KgUChckt3Z2W++mW9mHR3XgqNrqiumZIz9Iw8jKjOVM7mO8YvL1JliVBkic8KVpDHe0QofJ48fRZXZcXqxodQggJBVjDfGlHPXrbINFaQ6UiWVcFIoLYiBrV67VakpySt7SXA38LyJKwiTuEWYi+xPQATRV9vSyZQoiWErxpnZNVgYiWx+vpZKkxUHqrU/Jhmq/YkO+giN6acggmVaVaowRwDqqqJgGf2Z68yduSQ7IAHsw5D80PWCNvEkKpQ0FcrUVpoYjwDdkp5fSfVKpvYINMGtVxJVr9E14WDxsZtEmeJKIwPFhlwbiySCth63H9/ffvpsvQoiGN+11sAaGnk6N8GgWNboWho/hpnZk/swRw2VDdEVNELLbjT+szgry6ZLKWju/H1KDwrfZFtBuozzfe0DW2YwJBG0laFaprBB3fpyV0KRJUxAW63G7x7vtSY7PwgHF9wmYBKtlM5h4nrVrcCtKYk4LQyURbP1xv4bVcLvShkDjZlEOSNrJQm3ivU3ugWkk1HOL+xUviy+w64LJLciFeY8jzHMt9W6X0Ii3bLFazcWf4jWYg9gR0D572FRXezxf3UbRtVW6Q5S+9uIlCXf2emwfd/uTjhbS0FbUxKRfos2SrPX4GrnJoNzqrF97gzLBhabb138U0r/k0ZTe6j2QNLvBN1Lg+x0xvjLzc3XD+/g7ejKi1Zbxg2Td4gJmHl9aA/Pdqexz2XTOPso0CU5LciWm8v9YYwP62c0Z1sBWnVez9m1Mg1EjA/rp7aL/YmNQWvztIIXBv7RVrMYvzlbPJktz9LAmXqLqTMe0dCZhYulE45PF8tlOvMC7/Tt4N3+h1e7+caAuv54XnF423WXbEf+4mCL8WDT0m/mF2gPuc+CiXcS+p6TjjzfGU/I1JlORqGThn6wnIwXZ2EaDriHD/xOeK7v99+J2g/nhgnKmey16hUaWkEk2P4mCbdXwj18wJNvAAAA//8DAFBLAwQUAAYACAAAACEArkCL4XsCAAD/BQAAGAAAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbJRUXW/bMAx8H7D/YOi9sZ1m62rYLtCPNGkzYFi3vSsybQu1JU1Skma/fpTceKmKAe2bdaaOR4rH/OKp76ItaMOlKEg6SUgEgsmKi6YgP3/MT76QyFgqKtpJAQXZgyEX5ccP+U7qR9MC2AgZhClIa63K4tiwFnpqJlKBwD+11D21eNRNbJQGWvlLfRdPk+Rz3FMuyMCQ6bdwyLrmDK4l2/Qg7ECioaMW9ZuWK3Ng69lb6HqqHzfqhMleIcWad9zuPSmJepYtGyE1XXdY91M6o+zA7Q+v6HvOtDSythOkiwehr2s+j89jZCrzimMFru2Rhrogl2m2mpG4zH1/fnHYmaPvyNL1A3TALFT4TCRy7V9L+egClwglyGh8gGOkzPItXEHXFWRxhi/42+fAT0wQjxmOvw/Z5v7BvumogppuOvtd7hbAm9Zi2tlk+gl74FqRVftrMAzfAHNPpqPwa2ppmWu5i/A5UadR1A3HNEun/7lZ5szF3rhgfwUZDVazLZM83qJE9hwxHyJ8Ln/lNgQWIbAMgbsQuA+B1REQYx1jMaj/7cW4YKzatcVLnYfAbQgsQmAZAnchcB8CqyPghfbT92h3wS+0h8BtCCxCYBkCdyFwHwKrI+CF9tk7tF9i8Dg+6Tg+A98w98OA9qAb7w8TMblxQ5ziyI3oYMkbtOSpd8y/8DJXLS5CyxlapJbCOvPhyNi9wi0h5JUUz9vUXVS0ga9UN1yYqIPaewXtqAc/JRP8tlI5B52hsdbSWtkfTi3uSkBjJBPsTC2lPRyeeR/AblSkqAL9wP9g8nMSSc3RkX4ZFkRJbTXlFvNlHFXqZZX6asbVXf4FAAD//wMAUEsDBBQABgAIAAAAIQDflxGiRAEAAFECAAARAAgBZG9jUHJvcHMvY29yZS54bWwgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8klFrgzAUhd8H+w+Sd03UtrRBLWyjTysM5tjYW0huW5mJIclm++8XtXUWyh7vPSffPfeSbH2UdfADxlaNylEcERSA4o2o1D5Hb+UmXKLAOqYEqxsFOTqBRevi/i7jmvLGwItpNBhXgQ08SVnKdY4OzmmKseUHkMxG3qG8uGuMZM6XZo81419sDzghZIElOCaYY7gDhnokojNS8BGpv03dAwTHUIME5SyOoxj/eR0YaW8+6JWJU1bupP1O57hTtuCDOLqPthqNbdtGbdrH8Plj/LF9fu1XDSvV3YoDKjLBKTfAXGOKDE8Lf7iaWbf1N95VIB5OXr/RE7yPO0BABD4AHeJelPf08ancoCIh8Twki5DMy3hJ4xVNZ5/dyKv3XaChIc+D/yUmJCSzMElKsqDpks5XE+IFMOS+/gTFLwAAAP//AwBQSwMEFAAGAAgAAAAhAH/0V+5FAAAA3AAAACcAAAB4bC9wcmludGVyU2V0dGluZ3MvcHJpbnRlclNldHRpbmdzMS5iaW5iYKAMMLIws90BGsGsz8jAyMDJMIvbhCMFyOJniGBiAtIRTMxA0pHBhEJ7kLUzQjkgmgmIQfR/IHD3DEaxBgAAAP//AwBQSwMEFAAGAAgAAAAhADpd9BGaAQAAEAMAABAACAFkb2NQcm9wcy9hcHAueG1sIKIEASigAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnJLBbtswDIbvBfoOhu6NnG4ohkBWUaQretiwAEl6V2U6FipLgsQayZ5llx0G7A122tt0wB6jtI2mTttTbyR/4tdHUuJ829ishZiMdwWbTnKWgdO+NG5TsPXq6uQTyxIqVyrrHRRsB4mdy+MjsYg+QEQDKSMLlwpWI4YZ50nX0Kg0IdmRUvnYKKQ0brivKqPh0uv7Bhzy0zw/47BFcCWUJ2FvyAbHWYvvNS297vjSzWoXCFiKixCs0QppSvnV6OiTrzD7vNVgBR+LguiWoO+jwZ3MBR+nYqmVhTkZy0rZBII/F8Q1qG5pC2VikqLFWQsafcyS+U5rO2XZrUrQ4RSsVdEoh4TVtQ1JH9uQMMp/f349/P3x/+dvwUkfan04bh3H5qOc9g0UHDZ2BgMHCYeEK4MW0rdqoSK+ATwdA/cMA+6As6wBcHhzzNdPTC+98J77Jii3I2EffTHuLq3Dyl8qhKdtHhbFslYRSjrAftv7grimRUbbmcxr5TZQPvW8Frrb3wwfXE7PJvmHnM46qgn+/JXlIwAAAP//AwBQSwECLQAUAAYACAAAACEAQTeCz24BAAAEBQAAEwAAAAAAAAAAAAAAAAAAAAAAW0NvbnRlbnRfVHlwZXNdLnhtbFBLAQItABQABgAIAAAAIQC1VTAj9AAAAEwCAAALAAAAAAAAAAAAAAAAAKcDAABfcmVscy8ucmVsc1BLAQItABQABgAIAAAAIQCBPpSX8wAAALoCAAAaAAAAAAAAAAAAAAAAAMwGAAB4bC9fcmVscy93b3JrYm9vay54bWwucmVsc1BLAQItABQABgAIAAAAIQDsxPod4QEAAIgDAAAPAAAAAAAAAAAAAAAAAP8IAAB4bC93b3JrYm9vay54bWxQSwECLQAUAAYACAAAACEARUu2AuAAAAAwAQAAFAAAAAAAAAAAAAAAAAANCwAAeGwvc2hhcmVkU3RyaW5ncy54bWxQSwECLQAUAAYACAAAACEAO20yS8EAAABCAQAAIwAAAAAAAAAAAAAAAAAfDAAAeGwvd29ya3NoZWV0cy9fcmVscy9zaGVldDEueG1sLnJlbHNQSwECLQAUAAYACAAAACEAy6omh6QGAACTGgAAEwAAAAAAAAAAAAAAAAAhDQAAeGwvdGhlbWUvdGhlbWUxLnhtbFBLAQItABQABgAIAAAAIQDYENwiFwMAAAYIAAANAAAAAAAAAAAAAAAAAPYTAAB4bC9zdHlsZXMueG1sUEsBAi0AFAAGAAgAAAAhAK5Ai+F7AgAA/wUAABgAAAAAAAAAAAAAAAAAOBcAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbFBLAQItABQABgAIAAAAIQDflxGiRAEAAFECAAARAAAAAAAAAAAAAAAAAOkZAABkb2NQcm9wcy9jb3JlLnhtbFBLAQItABQABgAIAAAAIQB/9FfuRQAAANwAAAAnAAAAAAAAAAAAAAAAAGQcAAB4bC9wcmludGVyU2V0dGluZ3MvcHJpbnRlclNldHRpbmdzMS5iaW5QSwECLQAUAAYACAAAACEAOl30EZoBAAAQAwAAEAAAAAAAAAAAAAAAAADuHAAAZG9jUHJvcHMvYXBwLnhtbFBLBQYAAAAADAAMACYDAAC+HwAAAAA=\",\r\n" + 
	    			"	\"relationData\": \"eyJzaGVldHMiOlt7ImluZGV4IjowLCJjaGlsZHJlbiI6W3siaWQiOiI2MjZhYTEyMC04NDY1LTExZWEtYTA3Yi01ZGQ2NjE4MGZhZjYiLCJyb3ciOjMsImNvbCI6MSwicm93Q291bnQiOjYsImNvbENvdW50IjozLCJ0eXBlIjowLCJiaW5kaW5nIjoicXVlcnlfYWxsIiwiY2VsbHMiOltdLCJjaGlsZHJlbiI6W10sIl9fcGFyZW50SWQiOm51bGwsImNoaWxkIjp7ImlkIjoiNjU0OTdlMjAtODQ2NS0xMWVhLWEwN2ItNWRkNjYxODBmYWY2Iiwicm93IjoxLCJjb2wiOjAsInJvd0NvdW50IjoxLCJjb2xDb3VudCI6MywidHlwZSI6MSwiYmluZGluZyI6IiRqaW54aWQxLuWIl+ihqCIsImNlbGxzIjpbeyJpZCI6IjZkMzdmYWQwLTg0NjUtMTFlYS1hMDdiLTVkZDY2MTgwZmFmNiIsInJvdyI6MCwiY29sIjowLCJiaW5kaW5nIjoi6LSm5Y2VIiwiZW5hYmxlIjp0cnVlLCJlbmFibGVTY29wZSI6ZmFsc2UsImRhdGFUeXBlIjowLCJmb3JtYXQiOiIiLCJvcHRpb25zIjpbeyJvcHRpb24iOiJmb3JtYXRTdHJpbmciLCJ2YWx1ZSI6IiIsIm9wdGlvbnMiOnt9fSx7Im9wdGlvbiI6ImZvcm1hdERhdGUiLCJ2YWx1ZSI6IiIsIm9wdGlvbnMiOnt9fSx7Im9wdGlvbiI6ImZvcm1hdE51bSIsInZhbHVlIjoiIiwib3B0aW9ucyI6e319LHsib3B0aW9uIjoiY29udGVudFR5cGUiLCJ2YWx1ZSI6IiIsIm9wdGlvbnMiOnt9fSx7Im9wdGlvbiI6ImNlbGxMb2NhdGlvbiIsInZhbHVlIjoiIiwib3B0aW9ucyI6e319LHsib3B0aW9uIjoiZm9ybXVsYSIsInZhbHVlIjoiIiwib3B0aW9ucyI6e319LHsib3B0aW9uIjoiZmxhZyIsInZhbHVlIjoiIiwib3B0aW9ucyI6e319LHsib3B0aW9uIjoibWVyZ2UiLCJ2YWx1ZSI6MCwib3B0aW9ucyI6e319LHsib3B0aW9uIjoibWVyZ2VQcmlvcml0eSIsInZhbHVlIjowLCJvcHRpb25zIjp7fX0seyJvcHRpb24iOiJ1bmNvdmVyVmFsdWUiLCJ2YWx1ZSI6ZmFsc2V9LHsib3B0aW9uIjoidW5jb3ZlckZvcm11bGFWYWx1ZSIsInZhbHVlIjpmYWxzZX1dfV0sImNoaWxkcmVuIjpbXSwiX19wYXJlbnRJZCI6IjYyNmFhMTIwLTg0NjUtMTFlYS1hMDdiLTVkZDY2MTgwZmFmNiJ9fV0sImlzSGlkZGVuIjpmYWxzZSwiaGlkZGVuVmFsdWUiOiIifV19\",\r\n" + 
	    			"	\"formData\": null,\r\n" + 
	    			"	\"hrxData\": null,\r\n" + 
	    			"	\"zipData\": null\r\n" + 
	    			"}"));
	    }
	    
	
}
